create database AIRBNB;

USE AIRBNB;

CREATE TABLE IF NOT EXISTS HOST_TYPE (
ID_HOST_TYPE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
HT_DESCRIPTION varchar (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS REGION (
ID_REGION INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
REGION_NAME varchar (50) NOT NULL
);

CREATE TABLE IF NOT EXISTS COUNTRY (
ID_COUNTRY INT AUTO_INCREMENT PRIMARY KEY,
COUNTRY_NAME varchar (50) NOT NULL,
ID_REGION INT NOT NULL,
foreign key (ID_REGION) REFERENCES REGION(ID_REGION)
);

CREATE TABLE IF NOT EXISTS CITY (
ID_CITY INT AUTO_INCREMENT PRIMARY KEY,
CITY_NAME varchar (50) NOT NULL,
ID_COUNTRY INT NOT NULL,
foreign key (ID_COUNTRY) REFERENCES COUNTRY(ID_COUNTRY)
);

CREATE TABLE IF NOT EXISTS RANKING_LEVEL (
ID_RANKING_LEVEL INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
RL_DESCRIPTION varchar (30) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS GENDER (
ID_GENDER INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
G_DESCRIPTION varchar (30) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPIETOR (
ID_PROPIETOR INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
EMAIL varchar (50) UNIQUE NOT NULL,
ID_HOST_TYPE INT NOT NULL,
FIRST_NAME varchar (50) NOT NULL,
LAST_NAME VARCHAR (50) NOT NULL,
AGE INT NOT NULL,
GENDER INT NOT NULL,
foreign key (ID_HOST_TYPE) REFERENCES HOST_TYPE(ID_HOST_TYPE),
foreign key (GENDER) REFERENCES GENDER(ID_GENDER)
);

CREATE TABLE IF NOT EXISTS HOUSING_TYPE (
ID_HOUSING_TYPE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
HST_DESCRIPTION varchar (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PROPERTY (
ID_PROPERTY INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ADDRESS varchar (50) UNIQUE NOT NULL,
ID_PROPIETOR INT NOT NULL,
ID_CITY INT NOT NULL,
POSTAL_CODE varchar (30) NOT NULL,
ID_HOUSING_TYPE INT NOT NULL,
ROOM_NUMBER INT NOT NULL,
MAX_GUEST INT NOT NULL,
PRICE_PER_NIGHT decimal(6,2) NOT NULL,
foreign key (ID_PROPIETOR) REFERENCES PROPIETOR(ID_PROPIETOR),
foreign key (ID_CITY) REFERENCES CITY(ID_CITY),
foreign key (ID_HOUSING_TYPE) REFERENCES HOUSING_TYPE(ID_HOUSING_TYPE)
);

CREATE INDEX IND_POSTAL_CODE ON PROPERTY(POSTAL_CODE);

CREATE TABLE IF NOT EXISTS REGISTER_USER (
ID_REGISTER_USER INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
EMAIL varchar (50) UNIQUE NOT NULL,
FIRST_NAME varchar (50) NOT NULL,
LAST_NAME VARCHAR (50) NOT NULL,
ID_COUNTRY INT NOT NULL,
AGE INT NOT NULL,
GENDER INT NOT NULL,
foreign key (ID_COUNTRY) REFERENCES COUNTRY(ID_COUNTRY),
foreign key (GENDER) REFERENCES GENDER(ID_GENDER)
);

CREATE TABLE IF NOT EXISTS PAYMENT_METHOD (
ID_PAYMENT_METHOD INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
PM_DESCRIPTION varchar (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS BOOKING (
ID_BOOKING INT AUTO_INCREMENT PRIMARY KEY,
ID_USER INT NOT NULL,
ID_PROPERTY INT NOT NULL,
ARRIVING_DATE date NOT NULL,
LEAVING_DATE date NOT NULL,
ID_PAYMENT_METHOD int NOT NULL,
foreign key (ID_USER) REFERENCES REGISTER_USER(ID_REGISTER_USER),
foreign key (ID_PROPERTY) REFERENCES PROPERTY(ID_PROPERTY),
foreign key (ID_PAYMENT_METHOD) REFERENCES PAYMENT_METHOD(ID_PAYMENT_METHOD)
);

CREATE TABLE IF NOT EXISTS REVIEW (
ID_REVIEW INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_USER INT NOT NULL,
ID_PROPERTY INT NOT NULL,
ID_RANKING_LEVEL INT NOT NULL,
foreign key (ID_USER) REFERENCES REGISTER_USER(ID_REGISTER_USER),
foreign key (ID_PROPERTY) REFERENCES PROPERTY(ID_PROPERTY),
foreign key (ID_RANKING_LEVEL) REFERENCES RANKING_LEVEL(ID_RANKING_LEVEL)
);

CREATE TABLE IF NOT EXISTS SERVICE (
ID_SERVICE INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
S_DESCRIPTION varchar (50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS SERVICE_PROPERTY (
ID_SERVICE_PROPERTY INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
ID_PROPERTY INT NOT NULL,
ID_SERVICE INT NOT NULL,
foreign key (ID_PROPERTY) REFERENCES PROPERTY(ID_PROPERTY),
foreign key (ID_SERVICE) REFERENCES SERVICE(ID_SERVICE)
);